# Generated by Django 3.1.2 on 2020-10-18 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('desc', models.TextField()),
                ('picture', models.ImageField(upload_to='categories/images/')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=32)),
                ('LastName', models.CharField(max_length=32)),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('City', models.CharField(max_length=32)),
                ('State', models.CharField(max_length=32)),
                ('PostalCode', models.CharField(max_length=8)),
                ('Country', models.CharField(max_length=32)),
                ('BillingAddress', models.TextField()),
                ('BillingCity', models.CharField(max_length=32)),
                ('BillingRegion', models.CharField(max_length=32)),
                ('BillingPostalCode', models.CharField(max_length=8)),
                ('BillingCountry', models.CharField(max_length=32)),
                ('ShipAddress', models.TextField()),
                ('ShipCity', models.CharField(max_length=32)),
                ('ShipRegion', models.CharField(max_length=32)),
                ('ShipPostalCode', models.CharField(max_length=8)),
                ('ShipCountry', models.CharField(max_length=32)),
                ('DateEntered', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer_profile',
                'verbose_name_plural': 'customers_profile',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentType', models.CharField(max_length=32)),
                ('Allowed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.TextField()),
                ('Phone', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'shippers',
                'verbose_name_plural': 'shippers',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('title', models.CharField(choices=[('Mr', 'MR.'), ('Miss', 'MISS.'), ('Mrs', 'MRS.')], max_length=8)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=32)),
                ('payment_method', models.CharField(choices=[('cash', 'CASH ON DELIVERY'), ('netbanking', 'NET BANKING'), ('emi', 'EMI')], max_length=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDSKU', models.CharField(max_length=50)),
                ('vendor_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField()),
                ('qty_per_unit', models.IntegerField()),
                ('mrp', models.FloatField()),
                ('market_price', models.FloatField()),
                ('our_price', models.FloatField()),
                ('image', models.ImageField(upload_to='product/images/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.TextField()),
                ('PaymentID', models.TextField()),
                ('OrderDate', models.DateTimeField()),
                ('ShipDate', models.DateTimeField()),
                ('RequiredDate', models.DateTimeField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('TransactStatus', models.BooleanField(default=False)),
                ('Paid', models.BooleanField(default=False)),
                ('PaymentDate', models.DateTimeField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customerprofile')),
                ('ShipperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shippers')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orderss',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.CharField(max_length=32)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('IDSKU', models.CharField(max_length=50)),
                ('ShipDate', models.DateTimeField()),
                ('BillDate', models.DateTimeField(auto_now_add=True)),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orders')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name': 'orderdetail',
                'verbose_name_plural': 'orderdetails',
            },
        ),
    ]
